#!/bin/bash
# configure.sh - Auto-detects Steam/Proton/Heroic paths and writes bakkesmod.conf
set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)"
CONF_FILE="$DIR/bakkesmod.conf"

echo "=== BakkesMod-Linux Configuration ==="
echo

detect_steam_path() {
    local candidates=(
        "$HOME/.steam/steam"
        "$HOME/.var/app/com.valvesoftware.Steam/.steam/steam"
        "$HOME/.local/share/Steam"
    )
    for c in "${candidates[@]}"; do
        [ -d "$c" ] && { echo "$c"; return 0; }
    done
    return 1
}

detect_proton_paths() {
    local roots=(
        "$HOME/.local/share/Steam/compatibilitytools.d"
        "$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/compatibilitytools.d"
    )
    local found=()
    for root in "${roots[@]}"; do
        [ -d "$root" ] || continue
        while IFS= read -r -d '' d; do
            [ -x "$d/files/bin/wine" ] && found+=("$d")
        done < <(find "$root" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)
    done
    printf '%s\n' "${found[@]}"
}

detect_wine_prefixes() {
    local roots=("$HOME/Games/Heroic/Prefixes")
    local found=()
    for root in "${roots[@]}"; do
        [ -d "$root" ] || continue
        while IFS= read -r -d '' d; do
            found+=("$d")
        done < <(find "$root" -mindepth 1 -maxdepth 1 -type d -print0 2>/dev/null)
    done
    printf '%s\n' "${found[@]}"
}

detect_game_dir() {
    local root="$HOME/Games/Heroic"
    [ -d "$root" ] || return 1
    find "$root" -mindepth 1 -maxdepth 1 -iname "rocketleague" -type d 2>/dev/null | head -n1
}

pick_from_list() {
    local prompt="$1"; shift
    local options=("$@")
    if [ "${#options[@]}" -eq 0 ]; then
        return 1
    elif [ "${#options[@]}" -eq 1 ]; then
        echo "${options[0]}"
        return 0
    fi
    echo "$prompt" >&2
    local i=1
    for o in "${options[@]}"; do
        echo "  $i) $o" >&2
        i=$((i + 1))
    done
    read -rp "Choice [1-${#options[@]}]: " choice
    echo "${options[$((choice - 1))]}"
}

STEAM_PATH="$(detect_steam_path || true)"
[ -z "${STEAM_PATH:-}" ] && read -rp "Steam path not found. Enter manually: " STEAM_PATH
echo "Steam path: $STEAM_PATH"

mapfile -t PROTON_OPTIONS < <(detect_proton_paths)
if [ "${#PROTON_OPTIONS[@]}" -eq 0 ]; then
    read -rp "No GE-Proton found. Enter Proton path manually: " PROTON_PATH
else
    PROTON_PATH="$(pick_from_list "Select your Proton install:" "${PROTON_OPTIONS[@]}")"
fi
echo "Proton path: $PROTON_PATH"

mapfile -t PREFIX_OPTIONS < <(detect_wine_prefixes)
if [ "${#PREFIX_OPTIONS[@]}" -eq 0 ]; then
    read -rp "No Heroic Wine prefixes found. Enter Wine prefix path manually: " WINE_PREFIX
else
    WINE_PREFIX="$(pick_from_list "Select your Rocket League Wine prefix:" "${PREFIX_OPTIONS[@]}")"
fi
echo "Wine prefix: $WINE_PREFIX"

GAME_DIR="$(detect_game_dir || true)"
if [ -z "${GAME_DIR:-}" ]; then
    read -rp "Rocket League folder not auto-found. Enter it (blank to skip symlink step): " GAME_DIR
fi
echo "Game dir: ${GAME_DIR:-<none>}"

cat > "$CONF_FILE" <<EOF
# Auto-generated by configure.sh on $(date)
STEAM_PATH="$STEAM_PATH"
PROTON_PATH="$PROTON_PATH"
WINE_PREFIX="$WINE_PREFIX"
GAME_DIR="$GAME_DIR"
EOF

echo
echo "Saved config to $CONF_FILE"
echo "Next: run ./install.sh to download and install BakkesMod."
